### ISSUE TITLE
Remove extra "}" char in .format replacement field

### ISSUE THREAD

**Issue by wdennis** [consentfactory/ztpgenerator#2]
https://github.com/consentfactory/ztpgenerator/blob/3ba6b97bb7197da2c837a5449629113b53a7afd0/ztpgenerator.py#L177

Currently throws traceback:
```
Traceback (most recent call last):
  File "./ztpgenerator.py", line 214, in <module>
    ztpgenerator(csv_file)
  File "./ztpgenerator.py", line 177, in ztpgenerator
    with open("{}}dhcpd/dhcpd.j2".format(templates_path)) as t2_fh:
ValueError: Single '}' encountered in format string
```

**Comment by commitconfirm** [comment]
Thanks for the heads up on that! Resolved!
